# Generated by Django 5.2.7 on 2025-11-04 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedIP',
        ),
    ]
